In [1]:
import numpy as np
A = np.array([[1,2,3],
              [2,3,4]])
print(A)


[[1 2 3]
 [2 3 4]]


In [2]:
print('number of dim:',A.ndim)

number of dim: 2


In [3]:
print('shape:',A.shape)

shape: (2, 3)


In [4]:
print('size:',A.size)

size: 6


In [29]:
import numpy as np
A = np.array([[2,2.3,4],
             [2,3.2,4]])
A0 = np.zeros((3,4))
A1 = np.ones((2,3),dtype=np.int16)
Amin = np.empty((3,4))
Arange = np.arange(12).reshape((3,4))
Aline = np.linspace(1,10,6).reshape((2,3))
print(A)
print(A0)
print(A1)
print(Amin)
print(Arange)
print(Aline)

[[ 2.   2.3  4. ]
 [ 2.   3.2  4. ]]
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[1 1 1]
 [1 1 1]]
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[  1.    2.8   4.6]
 [  6.4   8.2  10. ]]


In [21]:
import numpy as np
Amin = np.empty((3,4))
print(Amin)

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [10]:
import numpy as np
a = np.array([10,20,30,40])
b = np.arange(4)
print(a,b)
print(a>20,b<3)
c = a-b
d = a+b
e = a*b
f = b**2
g = 10*np.sin(a)#cos tan等

print(c)
print(d)
print(e)
print(f)
print(g)

[10 20 30 40] [0 1 2 3]
[False False  True  True] [ True  True  True False]
[10 19 28 37]
[10 21 32 43]
[  0  20  60 120]
[0 1 4 9]
[-5.44021111  9.12945251 -9.88031624  7.4511316 ]


In [41]:
import numpy as np
a = np.array([[1,1],
             [0,1]])
b = np.arange(4).reshape(2,2)
print(a)
print(b)
c = a*b
c_dot = np.dot(a,b)
c_dot_1 = a.dot(b)
print(c)
print(c_dot)
print(c_dot_1)

[[1 1]
 [0 1]]
[[0 1]
 [2 3]]
[[0 1]
 [0 3]]
[[2 4]
 [2 3]]
[[2 4]
 [2 3]]


In [21]:
import numpy as np
a = np.random.random((2,4))
print(a)
print(np.sum(a))
print(np.max(a))
print(np.min(a))
print(np.sum(a,axis=1))
print(np.min(a,axis=0))
print(np.min(a,axis=1))

[[ 0.2706944   0.48027564  0.00835308  0.83170055]
 [ 0.31429675  0.54158937  0.87013878  0.25754769]]
3.57459626981
0.870138784946
0.00835308363163
[ 1.59102368  1.98357259]
[ 0.2706944   0.48027564  0.00835308  0.25754769]
[ 0.00835308  0.25754769]


In [40]:
import numpy as np
a = np.arange(2,14).reshape((3,4))

print(a)
print(np.argmin(a))#最小索引值
print(np.argmax(a))
print(np.mean(a))#与下一行代码相同
print(a.mean())
print(np.mean(a,axis=0))
print(np.median(a))#中位数
print(np.cumsum(a))#第i个数是前i个数相加
print(np.diff(a))#累差，i=i+1-i
#print(np.nonzero(a))
print(np.transpose(a))#矩阵的转置，行变列,同下
print(a.T)
print(np.clip(a,5,9))#阈值控制，大于某值就为某值，小于类似

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
0
11
7.5
7.5
[ 6.  7.  8.  9.]
7.5
[ 2  5  9 14 20 27 35 44 54 65 77 90]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]
 [ 5  9 13]]
[[ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]
 [ 5  9 13]]
[[5 5 5 5]
 [6 7 8 9]
 [9 9 9 9]]


In [14]:
import numpy as np
a = np.arange(3,15)
print(a)
print(a[3])#索引
b = np.arange(3,15).reshape(3,4)
print(b)
print(b[2])
print(b[1][1])
print(b[1,1])
print(b[1,:])
print(b[:,1])
print(b[1,1:3])
for row in b:
    print(row)
for col in b.T:
    print(col)
print(b.flatten())
for item in b.flat:
    print(item)

[ 3  4  5  6  7  8  9 10 11 12 13 14]
6
[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
[11 12 13 14]
8
8
[ 7  8  9 10]
[ 4  8 12]
[8 9]
[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]
[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]
[ 3  4  5  6  7  8  9 10 11 12 13 14]
3
4
5
6
7
8
9
10
11
12
13
14


In [17]:
import numpy as np
a = np.arange(3,15).reshape((3,4))
print(a)
print(a[1,1:3])
print(a.flatten())

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
[8 9]
[ 3  4  5  6  7  8  9 10 11 12 13 14]


In [39]:
import numpy as np

a = np.array([1,1,1])
b = np.array([2,2,2])
c = np.vstack((a,b))#上下合并
d = np.hstack((a,b))#左右合并
print(a.shape,b.shape)
print(c.shape)  
print(d)
print(d.shape)
print(a[np.newaxis,:])
print(a[:,np.newaxis])
A = a[:,np.newaxis]
B = b[:,np.newaxis]
e = np.vstack((A,B))
f = np.hstack((A,B))
print(e)
print(f)
C = np.concatenate((A,B,B,A),axis=1)
print(C)

(3,) (3,)
(2, 3)
[1 1 1 2 2 2]
(6,)
[[1 1 1]]
[[1]
 [1]
 [1]]
[[1]
 [1]
 [1]
 [2]
 [2]
 [2]]
[[1 2]
 [1 2]
 [1 2]]
[[1 2 2 1]
 [1 2 2 1]
 [1 2 2 1]]


In [43]:
print(e)


[[1]
 [1]
 [1]
 [2]
 [2]
 [2]]


In [11]:
import numpy as np
a = np.arange(12).reshape((3,4))
print(a)
print(np.split(a,2,axis=1))#1代表列<1>
print(np.split(a,3,axis=0))#<2>
print(np.array_split(a,3,axis=1))#<3>
print(np.vsplit(a,3))#<4>
print(np.hsplit(a,2))#<5>

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


In [6]:
import numpy as np
a = np.arange(4)
b = a
c = b
print(a)
b[0] = 1
print(a)
d = a.copy()
print(d)
c[3] = 0
print(d)
print(a)

[0 1 2 3]
[1 1 2 3]
[1 1 2 3]
[1 1 2 3]
[1 1 2 0]
